name: Publish to npm

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - 'tests/**'

jobs:
  checks:
    uses: ./.github/workflows/build-and-test.yaml

  # Build and publish to npm
  publish:
    name: Publish to npm
    needs: [checks] # Ensure checks completes successfully before publishing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build # Optional: Remove if your project doesn't need a build step

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}
